server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=doctor
spring.datasource.password=
spring.datasource.url=jdbc:mysql://39.105.193.82:3306/mybatis

mybatis.mapper-locations=classpath:mybatis_mapper/*.xml

spring.data.redis.database=0
spring.data.redis.host=39.105.193.82
spring.data.redis.port=6379
spring.data.redis.password=

spring.servlet.multipart.max-file-size = -1
spring.servlet.multipart.max-request-size = -1
server.tomcat.max-swallow-size = -1



# customized settings

oss.endpoint=https://oss-cn-beijing.aliyuncs.com
oss.bucket-name=music-p
oss.access-key-id=
oss.access-key-secret=

cache.expiration-minute=30
searching.cache-number=10
searching.page-length=50
